/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class view_Cpu */

typedef int jint;

#ifndef _Included_view_Cpu
#define _Included_view_Cpu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     view_Cpu
 * Method:    getCpu
 * Method:    getBattery
 * Signature: ()F
 */
JNIEXPORT jstring JNICALL Java_view_Cpu_getCpu
  (JNIEnv * env, jobject obj);

JNIEXPORT jint JNICALL Java_view_Cpu_getBattery
  (JNIEnv * env, jobject obj);

JNIEXPORT jobjectArray JNICALL Java_view_Cpu_getFileS
  (JNIEnv * env, jobject obj);

JNIEXPORT jstring JNICALL Java_view_Cpu_getMem
  (JNIEnv * env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
