/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class view_Cpu */

#ifndef _Included_view_Cpu
#define _Included_view_Cpu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     view_Cpu
 * Method:    getCpu
 * Signature: ()F
 */
JNIEXPORT String JNICALL Java_view_Cpu_getCpu
  (JNIEnv * env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
